# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
#en:
  #languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 乔小墓の主页
  params:
    description: 二次元退散！！！
  menu:
    main:
      - name: 关于我
        url: '#about'
        weight: 1
      - name: 日志
        url: '#post'
        weight: 2
